import { Dictionary } from "@/common/const";

export const _SharedConfig: MapSetting.RootObject = {
  /** 警员 */
  "source-police": {
    config: {
      type: "geojson",
      data: [],
      maxzoom: 18,
      minzoom: 5,
      clusterRadius: 80,
      cluster: true,
    },
    filter: {},
    layers: [
      {
        id: "layer-police-cluster",
        type: "symbol",
        sort: 1,
        filter: ["has", "point_count"],
        layout: {
          "visibility": "visible",
          "icon-image": Dictionary.POLICE_TYPE,
          "icon-anchor": "bottom",
          "text-field": "{point_count} 名",
          "icon-text-fit": "both",
          "icon-allow-overlap": true,
          "text-allow-overlap": true,
          "text-size": 14,
          "icon-size": 1,
          "text-offset": [0, 0],
        },
        paint: {
          "text-color": "#ffffff",
          "text-halo-width": 0.1,
          "text-halo-color": "#ffffff",
        },
      },
      {
        id: "layer-police-tips",
        type: "symbol",
        sort: 1,
        filter: ["!has", "point_count"],
        layout: {
          "icon-image": "{tag}",
          "icon-allow-overlap": true,
          "text-allow-overlap": true,
          "text-anchor": "top",
          "text-field": "{time}",
          "text-offset": [0, -4.7],
          "icon-offset": [0, -50],
          "text-optional": false,
          "text-size": 12,
          "icon-size": 1,
        },
        paint: {
          "text-color": "#ffffff",
          "text-halo-width": 0.1,
          "text-halo-color": "#ffffff",
        },
      },
      {
        id: "layer-police-uncluster",
        type: "symbol",
        sort: 1,
        filter: ["!has", "point_count"],
        layout: {
          "visibility": "visible",
          "icon-image": ["get", "imageName"],
          "icon-size": ["interpolate", ["linear"], ["zoom"], 5, 0.6, 8, 0.7, 16, 0.8, 18, 1],
          "icon-anchor": "bottom",
          "icon-allow-overlap": true,
          "text-allow-overlap": false,
          "symbol-sort-key": ["to-number", ["get", "key"]],
          "text-field": "{name}",
          "text-anchor": "top",
          "text-size": 14,
          "text-optional": true,
        },
        paint: {},
      },
    ],
  },
  /** 警车 */
  "source-jyzbl_zj_jc": {
    config: {
      type: "geojson",
      data: [],
      maxzoom: 18,
      clusterRadius: 80,
      cluster: true,
    },
    filter: {},
    layers: [
      {
        id: "layer-jyzbl_zj_jc-cluster",
        type: "symbol",
        sort: 2,
        filter: ["has", "point_count"],
        layout: {
          "icon-image": Dictionary.VEHICLE,
          "icon-anchor": "bottom",
          "text-field": "{point_count} 辆",
          "icon-text-fit": "both",
          "icon-allow-overlap": true,
          "text-allow-overlap": true,
          "text-size": 14,
          "icon-size": 1,
          "text-offset": [0, 0],
        },
        paint: {
          "text-color": "#ffffff",
          "text-halo-width": 0.1,
          "text-halo-color": "#ffffff",
        },
      },
      {
        id: "layer-jyzbl_zj_jc-uncluster",
        type: "symbol",
        sort: 2,
        filter: ["!", ["has", "point_count"]],
        layout: {
          "icon-image": ["get", "imageName"],
          "icon-size": ["interpolate", ["linear"], ["zoom"], 5, 0.5, 8, 0.6, 16, 0.7, 18, 0.9],
          "icon-anchor": "bottom",
          "icon-allow-overlap": true,
          "text-allow-overlap": false,
          "symbol-sort-key": ["to-number", ["get", "key"]],
          "text-field": "{name}",
          "text-anchor": "top",
          "text-size": 12,
          "text-optional": true,
        },
        paint: {},
      },
      {
        id: "layer-jyzbl_zj_jc-tips",
        type: "symbol",
        sort: 1,
        filter: ["all", ["==", "on", "1"], ["!has", "point_count"]],
        layout: {
          "icon-size": ["interpolate", ["linear"], ["zoom"], 5, 0.6, 8, 0.7, 16, 0.8, 18, 1],
          "icon-allow-overlap": true,
          "icon-anchor": "top",
          "icon-image": "{status}",
          "icon-offset": [28, -64],
        },
        paint: {},
      },
    ],
  },
  /** 无人机 */
  "source-jyzbl_zj_wrj": {
    config: {
      type: "geojson",
      data: [],
      maxzoom: 18,
      clusterRadius: 80,
      cluster: true,
    },
    filter: {},
    layers: [
      {
        id: "layer-jyzbl_zj_wrj-cluster",
        type: "symbol",
        sort: 6,
        filter: ["has", "point_count"],
        layout: {
          "icon-image": Dictionary.WURENJI,
          "icon-anchor": "bottom",
          "text-field": "{point_count} 台",
          "icon-text-fit": "both",
          "icon-allow-overlap": true,
          "text-allow-overlap": true,
          "text-size": 14,
          "icon-size": 1,
          "text-offset": [0, 0],
        },
        paint: {
          "text-color": "#ffffff",
          "text-halo-width": 0.1,
          "text-halo-color": "#ffffff",
        },
      },
      {
        id: "layer-jyzbl_zj_wrj-uncluster",
        type: "symbol",
        sort: 6,
        filter: ["!", ["has", "point_count"]],
        layout: {
          "icon-image": ["get", "imageName"],
          "icon-size": ["interpolate", ["linear"], ["zoom"], 5, 0.6, 8, 0.7, 16, 0.8, 18, 1],
          "icon-anchor": "bottom",
          "icon-allow-overlap": true,
          "text-allow-overlap": false,
          "symbol-sort-key": ["to-number", ["get", "key"]],
          "text-field": "{name}",
          "text-anchor": "top",
          "text-size": 14,
          "text-optional": true,
        },
        paint: {},
      },
    ],
  },
  /** 警务通 */
  "source-jyzbl_jwt": {
    config: {
      type: "geojson",
      data: [],
      maxzoom: 18,
      clusterRadius: 80,
      cluster: true,
    },
    filter: {},
    layers: [
      {
        id: "layer-jyzbl_jwt-cluster",
        type: "symbol",
        sort: 3,
        filter: ["has", "point_count"],
        layout: {
          "icon-image": Dictionary.POLICE_TONG,
          "icon-anchor": "bottom",
          "text-field": "{point_count} 个",
          "icon-text-fit": "both",
          "icon-allow-overlap": true,
          "text-allow-overlap": true,
          "text-size": 14,
          "icon-size": 1,
          "text-offset": [0, 0],
        },
        paint: {
          "text-color": "#ffffff",
          "text-halo-width": 0.1,
          "text-halo-color": "#ffffff",
        },
      },
      {
        id: "layer-jyzbl_jwt-uncluster",
        type: "symbol",
        sort: 3,
        filter: ["!", ["has", "point_count"]],
        layout: {
          "icon-image": ["get", "imageName"],
          "icon-size": ["interpolate", ["linear"], ["zoom"], 5, 0.6, 8, 0.7, 16, 0.8, 18, 1],
          "icon-anchor": "bottom",
          "icon-allow-overlap": true,
          "text-allow-overlap": false,
          "symbol-sort-key": ["to-number", ["get", "key"]],
          "text-field": "{name}",
          "text-anchor": "top",
          "text-size": 14,
          "text-optional": true,
        },
        paint: {},
      },
    ],
  },
  /** 对讲机 */
  "source-jyzbl_djj": {
    config: {
      type: "geojson",
      data: [],
      maxzoom: 18,
      clusterRadius: 80,
      cluster: true,
    },
    filter: {},
    layers: [
      {
        id: "layer-jyzbl_djj-cluster",
        type: "symbol",
        sort: 5,
        filter: ["has", "point_count"],
        layout: {
          "icon-image": Dictionary.INTERCOM,
          "icon-anchor": "bottom",
          "text-field": "{point_count} 个",
          "icon-text-fit": "both",
          "icon-allow-overlap": true,
          "text-allow-overlap": true,
          "text-size": 14,
          "icon-size": 1,
          "text-offset": [0, 0],
        },
        paint: {
          "text-color": "#ffffff",
          "text-halo-width": 0.1,
          "text-halo-color": "#ffffff",
        },
      },
      {
        id: "layer-jyzbl_djj-uncluster",
        type: "symbol",
        sort: 5,
        filter: ["!", ["has", "point_count"]],
        layout: {
          "icon-image": ["get", "imageName"],
          "icon-size": ["interpolate", ["linear"], ["zoom"], 5, 0.6, 8, 0.7, 16, 0.8, 18, 1],
          "icon-anchor": "bottom",
          "icon-allow-overlap": true,
          "text-allow-overlap": false,
          "symbol-sort-key": ["to-number", ["get", "key"]],
          "text-field": "{name}",
          "text-anchor": "top",
          "text-size": 14,
          "text-optional": true,
        },
        paint: {},
      },
    ],
  },
  /** 执法记录仪 */
  "source-jyzbl_zfjly": {
    config: {
      type: "geojson",
      data: [],
      maxzoom: 18,
      clusterRadius: 80,
      cluster: true,
    },
    filter: {},
    layers: [
      {
        id: "layer-jyzbl_zfjly-cluster",
        type: "symbol",
        sort: 4,
        filter: ["has", "point_count"],
        layout: {
          "icon-image": Dictionary.RECORDER,
          "icon-anchor": "bottom",
          "text-field": "{point_count} 个",
          "icon-text-fit": "both",
          "icon-allow-overlap": true,
          "text-allow-overlap": true,
          "text-size": 14,
          "icon-size": 1,
          "text-offset": [0, 0],
        },
        paint: {
          "text-color": "#ffffff",
          "text-halo-width": 0.1,
          "text-halo-color": "#ffffff",
        },
      },
      {
        id: "layer-jyzbl_zfjly-uncluster",
        type: "symbol",
        sort: 4,
        filter: ["!", ["has", "point_count"]],
        layout: {
          "icon-image": ["get", "imageName"],
          "icon-size": ["interpolate", ["linear"], ["zoom"], 5, 0.6, 8, 0.7, 16, 0.8, 18, 1],
          "icon-anchor": "bottom",
          "icon-allow-overlap": true,
          "text-allow-overlap": false,
          "symbol-sort-key": ["to-number", ["get", "key"]],
          "text-field": "{name}",
          "text-anchor": "top",
          "text-size": 14,
          "text-optional": true,
        },
        paint: {},
      },
    ],
  },
  /** 监控 */
  "source-jyzbl_jk_jklx": {
    config: {
      type: "geojson",
      data: [],
      maxzoom: 18,
      clusterRadius: 80,
      cluster: true,
    },
    filter: {},
    layers: [
      {
        id: "layer-jyzbl_jk_jklx-cluster",
        type: "symbol",
        sort: 7,
        filter: ["has", "point_count"],
        layout: {
          "icon-image": Dictionary.MONITOR_TYPE,
          "icon-anchor": "bottom",
          "text-field": "{point_count} 个",
          "icon-text-fit": "both",
          "icon-allow-overlap": true,
          "text-allow-overlap": true,
          "text-size": 14,
          "icon-size": 1,
          "text-offset": [0, 0],
          "text-optional": false,
        },
        paint: {
          "text-color": "#ffffff",
          "text-halo-width": 0.1,
          "text-halo-color": "#ffffff",
        },
      },
      {
        id: "layer-jyzbl_jk_jklx-uncluster",
        type: "symbol",
        sort: 7,
        filter: ["!", ["has", "point_count"]],
        layout: {
          "icon-image": ["get", "imageName"],
          "icon-size": ["interpolate", ["linear"], ["zoom"], 5, 0.6, 8, 0.7, 16, 0.8, 18, 1],
          "icon-anchor": "bottom",
          "icon-allow-overlap": true,
          "text-allow-overlap": false,
          "symbol-sort-key": ["to-number", ["get", "key"]],
          "text-field": "{name}",
          "text-anchor": "top",
          "text-size": 14,
          "text-optional": true,
        },
        paint: {},
      },
    ],
  },
  /** 兴趣点位 */
  "source-interest-point": {
    config: {
      type: "geojson",
      data: [],
      maxzoom: 18,
    },
    filter: {
      subClass: [],
      id: [],
    },
    layers: [
      {
        id: "layer-interest-point",
        type: "symbol",
        sort: 8,
        filter: ["==", "$type", "Point"],
        layout: {
          "icon-image": ["get", "imageName"],
          "icon-size": ["interpolate", ["linear"], ["zoom"], 5, 0.6, 8, 0.7, 16, 0.8, 18, 1],
          "icon-anchor": "bottom",
          "icon-allow-overlap": true,
          "text-allow-overlap": false,
          "symbol-sort-key": ["to-number", ["get", "key"]],
          "text-field": "{name}",
          "text-anchor": "top",
          "text-size": 12,
          "text-optional": true,
        },
        paint: {},
      },
      {
        id: "layer-interest-area",
        type: "fill",
        sort: 8,
        filter: ["!=", "$type", "Point"],
        layout: {
          "visibility": "none",
        },
        paint: {
          "fill-color": ["get", "areaColour"],
          "fill-opacity": 0.4,
          "fill-border-width": ["get", "lineType"],
          "fill-border-color": ["get", "lineColour"],
        },
      },
    ],
  },
};
